version: '3'

services:
  web:
    container_name: web
    image: bluekeymusic/dashboard:latest
    networks:
      - bluekey_network
    ports:
      - 80:8080
  dev:
    container_name: dev

networks:
  bluekey_network:
    driver: bridge
