spring:
  config:
    import:
      - classpath:application-aws.yml
      - classpath:application-auth.yml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/bluekey;MODE=MySQL;NON_KEYWORDS=value;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
  server:
    host: http://localhost:8080
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        globally_quoted_identifiers: true
#        globally_quoted_identifiers_skip_column_definitions: true
        show_sql: true
        format_sql:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-h2.sql
        - classpath:sql/data.sql

logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

springdoc:
  packages-to-scan: com.github.bluekey
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true