name: CD with Gradle

on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - Set application.yml
      run: |
        cd ./src/main/resources
        touch ./application-prod.yml
        echo "${{ secrets.application }}" > ./application-prod.yml

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test --stacktrace

    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/dashboard .
        docker push ${{ secrets.DOCKER_REPO }}/dashboard

    - name: Deploy
      uses: appleboy/ssh-action@master
      host: ${{ secrets.WAS_HOST }}
        username: ${{ secrets.WAS_USERNAME }}
        key: ${{ secrets.WAS_KEY }}
        port: ${{ secrets.WAS_SSH_PORT }}
        script: |
          cd /home/ubuntu/bluekey/
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker rm -f $(sudo docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          sudo docker-compose up -d
          sudo docker image prune -f